all:
  hosts:
    migrating-host:
      ansible_ssh_host: 172.31.31.101
      ansible_ssh_user: vyos
      ansible_ssh_pass: "{{ lookup('env', 'test') }}"


    # vyos-router02:
    #   ansible_host: *
    #   ansible_port: 9999
    #   ansible_user: vyos
    #   ansible_network_os: vyos
    #   ansible_password: test123
